version: '3.8'

services:
  voting-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./static:/app/static:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Опциональный Redis для production (если захотите использовать вместо in-memory storage)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

  # Опциональная PostgreSQL для production
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: voting_system
  #     POSTGRES_USER: voting_user
  #     POSTGRES_PASSWORD: secure_password_change_this
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

# volumes:
#   redis_data:
#   postgres_data:
